package services

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"time"
)

const (
	defaultQuanpanTokenEndpoint  = "https://quanpan.xyz/api/auth/token"
	defaultQuanpanSearchEndpoint = "https://quanpan.xyz/api/search"
	maxQuanpanTokenBodySize      = 256 << 10
	maxQuanpanSearchBodySize     = 8 << 20
	quanpanBrowserUserAgent      = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36"
)

// QuanpanSearchResult is the direct cloud-drive link returned by quanpan.
type QuanpanSearchResult struct {
	URL      string `json:"url"`
	Password string `json:"password"`
	Note     string `json:"note"`
	Datetime string `json:"datetime"`
}

type quanpanTokenResponse struct {
	Code int `json:"code"`
	Data struct {
		Token string `json:"token"`
		TTLMS int64  `json:"ttl_ms"`
	} `json:"data"`
}

type quanpanSearchResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    struct {
		Total        int64                            `json:"total"`
		MergedByType map[string][]QuanpanSearchResult `json:"merged_by_type"`
	} `json:"data"`
}

// QuanpanClient obtains quanpan's short-lived server-issued token and uses it
// for video searches. The token's signature is not generated by the browser.
type QuanpanClient struct {
	tokenEndpoint  string
	searchEndpoint string
	httpClient     *http.Client

	tokenMu        sync.Mutex
	token          string
	tokenRefreshAt time.Time
}

func NewQuanpanClient() *QuanpanClient {
	return NewQuanpanClientWithEndpoints(defaultQuanpanTokenEndpoint, defaultQuanpanSearchEndpoint, nil)
}

// NewQuanpanClientWithEndpoints allows isolated tests to provide both API endpoints.
func NewQuanpanClientWithEndpoints(tokenEndpoint, searchEndpoint string, client *http.Client) *QuanpanClient {
	if client == nil {
		client = &http.Client{Timeout: 35 * time.Second}
	}
	return &QuanpanClient{
		tokenEndpoint:  strings.TrimSpace(tokenEndpoint),
		searchEndpoint: strings.TrimSpace(searchEndpoint),
		httpClient:     client,
	}
}

// Search returns results for one supported provider (quark or xunlei).
func (q *QuanpanClient) Search(ctx context.Context, query, provider string) ([]QuanpanSearchResult, error) {
	provider = strings.ToLower(strings.TrimSpace(provider))
	if provider != "quark" && provider != "xunlei" {
		return nil, fmt.Errorf("quanpan 不支持网盘类型 %q", provider)
	}
	if strings.TrimSpace(q.searchEndpoint) == "" {
		return nil, fmt.Errorf("quanpan 搜索地址未配置")
	}

	payload, err := json.Marshal(struct {
		Keyword    string   `json:"kw"`
		Result     string   `json:"res"`
		Source     string   `json:"src"`
		CloudTypes []string `json:"cloud_types"`
	}{
		Keyword:    strings.TrimSpace(query),
		Result:     "quark,xunlei",
		Source:     "all",
		CloudTypes: []string{provider},
	})
	if err != nil {
		return nil, fmt.Errorf("构造 quanpan 搜索请求失败: %w", err)
	}

	token, err := q.getToken(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := q.doSearch(ctx, payload, query, token)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode == http.StatusForbidden {
		resp.Body.Close()
		q.invalidateToken(token)
		token, err = q.getToken(ctx)
		if err != nil {
			return nil, err
		}
		resp, err = q.doSearch(ctx, payload, query, token)
		if err != nil {
			return nil, err
		}
	}
	defer resp.Body.Close()
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return nil, fmt.Errorf("quanpan 搜索服务返回 HTTP %d", resp.StatusCode)
	}

	body, err := readLimitedBody(resp.Body, maxQuanpanSearchBodySize)
	if err != nil {
		return nil, fmt.Errorf("读取 quanpan 搜索结果失败: %w", err)
	}
	var upstream quanpanSearchResponse
	if err := json.Unmarshal(body, &upstream); err != nil {
		return nil, fmt.Errorf("解析 quanpan 搜索结果失败: %w", err)
	}
	if upstream.Code != 0 {
		message := NormalizeMelostText(upstream.Message, 160)
		if message == "" {
			message = "未知错误"
		}
		return nil, fmt.Errorf("quanpan 搜索失败: %s", message)
	}

	items := make([]QuanpanSearchResult, 0, len(upstream.Data.MergedByType[provider]))
	seen := make(map[string]int)
	for _, item := range upstream.Data.MergedByType[provider] {
		item.URL = strings.TrimSpace(item.URL)
		item.Password = NormalizeMelostText(item.Password, 20)
		item.Note = NormalizeMelostText(item.Note, 240)
		item.Datetime = NormalizeMelostText(item.Datetime, 40)
		if item.URL == "" || item.Note == "" {
			continue
		}
		item.URL = quanpanURLWithPassword(item.URL, item.Password)
		key := quanpanURLKey(item.URL)
		if index, exists := seen[key]; exists {
			if items[index].Password == "" && item.Password != "" {
				items[index] = item
			}
			continue
		}
		seen[key] = len(items)
		items = append(items, item)
	}
	return items, nil
}

func quanpanURLWithPassword(rawURL, password string) string {
	password = strings.TrimSpace(password)
	if password == "" {
		return rawURL
	}
	parsed, err := url.Parse(rawURL)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return rawURL
	}
	values := parsed.Query()
	if values.Get("pwd") != "" || values.Get("password") != "" {
		return rawURL
	}
	values.Set("pwd", password)
	parsed.RawQuery = values.Encode()
	return parsed.String()
}

func quanpanURLKey(rawURL string) string {
	parsed, err := url.Parse(rawURL)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return rawURL
	}
	values := parsed.Query()
	values.Del("pwd")
	values.Del("password")
	parsed.RawQuery = values.Encode()
	parsed.Fragment = ""
	return parsed.String()
}

func (q *QuanpanClient) doSearch(ctx context.Context, payload []byte, query, token string) (*http.Response, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, q.searchEndpoint, bytes.NewReader(payload))
	if err != nil {
		return nil, fmt.Errorf("创建 quanpan 搜索请求失败: %w", err)
	}
	q.setBrowserHeaders(req)
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Origin", endpointOrigin(q.searchEndpoint))
	req.Header.Set("Referer", endpointOrigin(q.searchEndpoint)+"/?q="+url.QueryEscape(strings.TrimSpace(query)))
	req.Header.Set("X-QP-K", token)

	resp, err := q.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("quanpan 搜索请求失败: %w", err)
	}
	return resp, nil
}

func (q *QuanpanClient) getToken(ctx context.Context) (string, error) {
	q.tokenMu.Lock()
	defer q.tokenMu.Unlock()

	if q.token != "" && time.Now().Before(q.tokenRefreshAt) {
		return q.token, nil
	}
	if strings.TrimSpace(q.tokenEndpoint) == "" {
		return "", fmt.Errorf("quanpan 令牌地址未配置")
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, q.tokenEndpoint, nil)
	if err != nil {
		return "", fmt.Errorf("创建 quanpan 令牌请求失败: %w", err)
	}
	q.setBrowserHeaders(req)
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Referer", endpointOrigin(q.tokenEndpoint)+"/")

	resp, err := q.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("quanpan 令牌请求失败: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		return "", fmt.Errorf("quanpan 令牌服务返回 HTTP %d", resp.StatusCode)
	}
	body, err := readLimitedBody(resp.Body, maxQuanpanTokenBodySize)
	if err != nil {
		return "", fmt.Errorf("读取 quanpan 令牌失败: %w", err)
	}
	var upstream quanpanTokenResponse
	if err := json.Unmarshal(body, &upstream); err != nil {
		return "", fmt.Errorf("解析 quanpan 令牌失败: %w", err)
	}
	token := strings.TrimSpace(upstream.Data.Token)
	if upstream.Code != 0 || token == "" || len(token) > 512 || strings.ContainsAny(token, "\r\n") {
		return "", fmt.Errorf("quanpan 未返回有效令牌")
	}

	ttl := time.Duration(upstream.Data.TTLMS) * time.Millisecond
	if ttl <= 0 {
		ttl = 15 * time.Minute
	}
	cacheFor := ttl - 3*time.Minute
	if cacheFor <= 0 {
		cacheFor = ttl / 2
	}
	q.token = token
	q.tokenRefreshAt = time.Now().Add(cacheFor)
	return token, nil
}

func (q *QuanpanClient) invalidateToken(token string) {
	q.tokenMu.Lock()
	defer q.tokenMu.Unlock()
	if q.token == token {
		q.token = ""
		q.tokenRefreshAt = time.Time{}
	}
}

func (q *QuanpanClient) setBrowserHeaders(req *http.Request) {
	req.Header.Set("Accept-Language", "zh-CN,zh;q=0.9")
	req.Header.Set("Cache-Control", "no-cache")
	req.Header.Set("Pragma", "no-cache")
	req.Header.Set("Sec-Fetch-Dest", "empty")
	req.Header.Set("Sec-Fetch-Mode", "cors")
	req.Header.Set("Sec-Fetch-Site", "same-origin")
	req.Header.Set("User-Agent", quanpanBrowserUserAgent)
}

func endpointOrigin(rawEndpoint string) string {
	parsed, err := url.Parse(rawEndpoint)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return ""
	}
	return parsed.Scheme + "://" + parsed.Host
}

func readLimitedBody(reader io.Reader, limit int64) ([]byte, error) {
	body, err := io.ReadAll(io.LimitReader(reader, limit+1))
	if err != nil {
		return nil, err
	}
	if int64(len(body)) > limit {
		return nil, fmt.Errorf("响应超过 %d 字节限制", limit)
	}
	return body, nil
}

// QuanpanResultID creates a stable, opaque document id for staging results.
func QuanpanResultID(item QuanpanSearchResult) string {
	digest := sha256.Sum256([]byte(item.URL + "\x00" + item.Note))
	return "quanpan-" + hex.EncodeToString(digest[:])[:32]
}
